FROM node:14.16.0-alpine

COPY ./AMR_Interop_Standard.json /app/AMR_Interop_Standard.json
COPY ./examples/statusReport1.json /app/examples/statusReport1.json
COPY ./MassRobotics-AMR-Receiver /app/MassRobotics-AMR-Receiver
WORKDIR /app/MassRobotics-AMR-Receiver
RUN npm run install-server

ENTRYPOINT npm run start
